// <auto-generated />
namespace PlanTogetherDotNetAPI.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddMissionIdToComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMissionIdToComment));
        
        string IMigrationMetadata.Id
        {
            get { return "202303080539379_AddMissionIdToComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
